# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Ryab Ranjitkar/Downloads/project_2/project_2.srcs/sources_1/ip/clk_mmcm/clk_mmcm.xci
# IP: The module: 'clk_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Ryab Ranjitkar/Downloads/project_2/project_2.gen/sources_1/ip/clk_mmcm/clk_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Ryab Ranjitkar/Downloads/project_2/project_2.gen/sources_1/ip/clk_mmcm/clk_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Ryab Ranjitkar/Downloads/project_2/project_2.gen/sources_1/ip/clk_mmcm/clk_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Ryab Ranjitkar/Downloads/project_2/project_2.srcs/sources_1/ip/clk_mmcm/clk_mmcm.xci
# IP: The module: 'clk_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Ryab Ranjitkar/Downloads/project_2/project_2.gen/sources_1/ip/clk_mmcm/clk_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Ryab Ranjitkar/Downloads/project_2/project_2.gen/sources_1/ip/clk_mmcm/clk_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Ryab Ranjitkar/Downloads/project_2/project_2.gen/sources_1/ip/clk_mmcm/clk_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
